# Generated by Django 4.0.5 on 2022-06-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='motorpool.brand'),
        ),
    ]
