# Generated by Django 4.0.5 on 2022-08-13 09:38

from django.db import migrations, models
import motorpool.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0009_brand_logo_alter_vehiclepassport_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=motorpool.models.get_upload_to_auto),
        ),
    ]
